site_name: Galileo Generative AI Reference Sample
site_description: Galileo Generative AI Reference Sample
repo_name: aws-genai-conversational-rag-reference
repo_url: https://github.com/aws-samples/aws-genai-conversational-rag-reference/
site_url: https://aws-samples.github.io/aws-genai-conversational-rag-reference/
copyright: Copyright &copy; 2024 Amazon Web Services, Inc.
use_directory_urls: false
docs_dir: content
extra_css:
  - assets/stylesheets/extra.css

nav:
  - ...

extra:
  social:
    - icon: fontawesome/brands/aws
      name: Amazon Web Services, Inc.
      link: https://aws.amazon.com

theme:
  name: material
  font: false
  logo: assets/images/logo.png
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  custom_dir: content/overrides
  palette:
    scheme: default
  features:
    - content.code.copy
    - toc.follow
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - header.autohide

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - abbr
  - admonition
  - tables
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      base_path: content/_
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - toc:
      toc_depth: 4
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      provider: github
      user: aws
      repo: pdk

plugins:
  - awesome-pages:
      filename: .pages.yml
  - git-revision-date
  - search
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
